version: '3'
services:
  fastapi-distances-calculator:
    image: ${HUB_REPOSITORY}/fastapi-distances-calculator:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8000"
    volumes:
      - ./data:/app/csv
      - ./logs:/app/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 5m
      timeout: 30s
      retries: 5
      start_period: 30s
